services:
  database:
    image: 'postgis/postgis:17-3.5'
    container_name: weather-db
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgres-weather-db/data/:/var/lib/postgresql/data/

  staging-database:
    image: 'postgis/postgis:17-3.5'
    container_name: staging-weather-db
    ports:
      - 5000:5432
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgres-staging-weather-db/data/:/var/lib/staging-postgresql/data/
