services:
  weather-database:
    image: 'postgis/postgis:17-3.5'
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf", "-c", "hba_file=/etc/pg_hba.conf"]
    container_name: weather-db
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgres-weather-db/data/:/var/lib/postgresql/data/
      - ./configs/pg_hba.conf:/etc/pg_hba.conf
      - ./configs/postgresql.conf:/etc/postgresql.conf

  staging-weather-database:
    image: 'postgis/postgis:17-3.5'
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf", "-c", "hba_file=/etc/pg_hba.conf"]
    container_name: staging-weather-db
    ports:
      - 5000:5432
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgres-staging-weather-db/data/:/var/lib/postgresql/data/
      - ./configs/pg_hba.conf:/etc/pg_hba.conf
      - ./configs/postgresql.conf:/etc/postgresql.conf
